### PR TITLE
Add new entities for clean count, true detect, and clean preference

### LINKED ISSUE #254: Set "True Detect" on Deebot T8/N8/T9
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Is your feature request related to a problem?

For some users (including me), Deebot's True Detect Obstacle Avoidance functionality does not work well in some rooms of the house where there are reflective kickboards at robot level. The reflections cause the robot to believe there is an obstacle in the way, and thus results in the robot doing circles in these areas and not cleaning the space.

### Suggested solution

It would be great if this integration supported controlling this parameter of the robot.  I have implemented this functionality previously in my client library for the Deebot T8, but am looking to move to this integration as something with better support (including map view)

https://github.com/nickw444/deebot-t8/blob/dcf2015cb050d19d93afe17656c3a16737e08079/deebot_t8/entity.py#L411-L417

### Api example request

https://github.com/nickw444/deebot-t8/blob/dcf2015cb050d19d93afe17656c3a16737e08079/deebot_t8/entity.py#L411-L417

### Alternatives you've considered

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nickw444**
As discussed in #254. Closes #254 

Depends on changes in https://github.com/DeebotUniverse/client.py/pull/163 to be merged & released.

Adds 3 new entities:

- TrueDetect switch: Enable/Disable "True Detect Obstacle Avoidance" technology
- Clean Count: Set the number of times to clean the area. From testing any integer works - it's possible to clean areas more than twice!
- Clean Preference switch: Enable/Disable "Auto cleaning" mode - I named the switch after the API name, but happy to change this to "Cleaning Preference" to align more closely with the terminology used in the app.

image

### CODE REVIEW

**Comment by edenhaus** [comment]
What really happens when yo switch Clean Preference?
I cannot find this option on my bot

**Comment by nickw444** [comment]
> What really happens when yo switch Clean Preference?

It turns on automatic cleaning preference, which essentially is clean count/vacuum power/water flow levels specified on a per-room basis in the app, allowing for more refined cleaning, rather than a one sized fits every room approach.

|     |     |
|---|---|
| IMG_9468 | IMG_9469 |

**Comment by edenhaus** [comment]
I would love that my model would support this too...
Do you know, if there is a possibility to find out, which command are supported by which model?

**Comment by nickw444** [comment]
Wow I am surprised it is not a feature on all robots! I am not sure there is a way in the API to determine whether it supports it or not, but I would guess that maybe the call to `getCleanPreference` might fail on unsupported robots? It's hard for me to know since I only have the Ozmo T8.

**Comment by edenhaus** [comment]
Will release the client library this weekend, sorry for the delay 😊

**Comment by edenhaus** [comment]
Sorry I have forgotten to notify you. The new library version is already included in the dev branch. Can you merge it in your branch?

Can you tell me please the class of your model?
So I will activate these sensor only for your model until we have setup proper knowledgebase in the library

**Comment by nickw444** [comment]
Just merged in `dev` into this PR.

> Can you tell me please the class of your model?

Yep it's a [Deebot Osmo T8](https://www.ecovacs.com/global/deebot-robotic-vacuum-cleaner/DEEBOT-OZMO-T8)

**Comment by nickw444** [comment]
Started primarily using this integration over the weekend! Works great. I think I'll likely archive my own project(s) - [deebot-t8](https://github.com/nickw444/deebot-t8) and [deebot-t8-hass](https://github.com/nickw444/deebot-t8-hass) and link to this project as it has much better support for other robots.

**Comment by edenhaus** [comment]
👍

**Pull request merged**
